site:
    title: "Lyndon Li's Blog"
    subtitle: "From tester to Full-stack"
    limit: 10
    theme: theme
    lang: zh
    url: "http://blog.lyndon.pw"
    comment: username
    logo: "-/images/avatar.png"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "Lyndon"
        intro: "一个保持清醒的沉睡者"
        avatar: "-/images/avatar.png"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - "README.md"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
